"""统一业务错误码定义。"""

from enum import IntEnum


class ErrorCode(IntEnum):
    VALIDATION_ERROR = 1001
    PERMISSION_DENIED = 1002
    RESOURCE_NOT_FOUND = 1003
    EXTERNAL_SOURCE_ERROR = 2001
    DATABASE_ERROR = 3001
    INTERNAL_ERROR = 9000


# 向后兼容：现有 `from astock.core.error_codes import VALIDATION_ERROR` 仍可用
VALIDATION_ERROR = ErrorCode.VALIDATION_ERROR
PERMISSION_DENIED = ErrorCode.PERMISSION_DENIED
RESOURCE_NOT_FOUND = ErrorCode.RESOURCE_NOT_FOUND
EXTERNAL_SOURCE_ERROR = ErrorCode.EXTERNAL_SOURCE_ERROR
DATABASE_ERROR = ErrorCode.DATABASE_ERROR
INTERNAL_ERROR = ErrorCode.INTERNAL_ERROR
